# See help here: https://github.com/marketplace/actions/labeler

Geti Library:
  - changed-files:
      - any-glob-to-any-file:
        - "library/**/*"

Geti Backend:
  - changed-files:
      - any-glob-to-any-file:
          - "application/backend/**/*"
          - "application/docker/**/*"

Geti UI:
  - changed-files:
      - any-glob-to-any-file:
          - "application/ui/**/*"

TEST:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tests/**/*"

DOC:
  - changed-files:
      - any-glob-to-any-file:
          - "**/docs/**/*"
          - "**/*.md"
          - "LICENSE"
          - "NOTICE"

BUILD:
  - changed-files:
      - any-glob-to-any-file:
          - ".ci/**/*"
          - ".github/**/*"
          - "**/.pre-commit-config.yaml"
          - "**/pyproject.toml"
          - "**/tox.ini"
          - "**/Dockerfile"
          - "markdownlint.yaml"
          - "MANIFEST.in"

DEPENDENCY:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pyproject.toml"
