id: instance-segmentation-rfdetr-2xl
name: RF-DETR-Seg-2XL

pretrained_weights:
  source: direct_link
  url: https://storage.googleapis.com/rfdetr/rf-detr-seg-2xl-ft.pth
  sha_sum: f6e06ac5ebafd3f9f6f01c55a7f53b8785a1697037063a6adeb737c4c6ce4838

description: "RF-DETR for instance segmentation extends the RF-DETR object detector with mask prediction capabilities, providing high-accuracy instance segmentation with real-time performance."
stats:
  gigaflops: 299.2
  trainable_parameters: 38.7
  benchmark_metrics:
    coco_map_50_95: 49.9
    coco_map_50: 73.1

hyperparameters:
  training:
    learning_rate: 0.0001
    weight_decay: 0.0001
    batch_size: 4
    early_stopping:
      patience: 15
    scheduler:
      factor: 0.1
      patience: 10
    gradient_clip:
      enable: true
      max_grad_norm: 0.1
    gradient_accumulation:
      enable: true
      batches: 4
    allowed_values_input_size:
      - 480
      - 528
      - 576
      - 624
      - 672
      - 720
      - 768
      - 864
    input_size_width: 768
    input_size_height: 768
  dataset_preparation:
    augmentation:
      random_zoom_out:
        enable: true
        fill: 0
        side_range:
          - 1.0
          - 4.0
        probability: 0.5
      iou_random_crop:
        enable: true
        probability: 1.0
        min_scale: 0.3
        max_scale: 1.0
