id: instance-segmentation-rfdetr-l
name: RF-DETR-Seg-L

pretrained_weights:
  source: direct_link
  url: https://storage.googleapis.com/rfdetr/rf-detr-seg-l-ft.pth
  sha_sum: ca7b7c630ba22496067cc4f034c4e70c8e47fd7adcea04c3a49aa8c1755cbe6b

description: "RF-DETR for instance segmentation extends the RF-DETR object detector with mask prediction capabilities, providing high-accuracy instance segmentation with real-time performance."
stats:
  gigaflops: 118.2
  trainable_parameters: 35.9
  benchmark_metrics:
    coco_map_50_95: 47.1
    coco_map_50: 70.5

hyperparameters:
  training:
    learning_rate: 0.0001
    weight_decay: 0.0001
    early_stopping:
      patience: 15
    scheduler:
      factor: 0.1
      patience: 10
    gradient_clip:
      enable: true
      max_grad_norm: 0.1
    allowed_values_input_size:
      - 336
      - 432
      - 480
      - 504
      - 528
      - 576
      - 624
      - 768
    input_size_width: 504
    input_size_height: 504
  dataset_preparation:
    augmentation:
      random_zoom_out:
        enable: true
        fill: 0
        side_range:
          - 1.0
          - 4.0
        probability: 0.5
      iou_random_crop:
        enable: true
        probability: 1.0
        min_scale: 0.3
        max_scale: 1.0
