name: install-common-deps
description: Setup common tools and dependencies used across multiple workflows

inputs:
  install-just:
    description: Install the 'just' command runner
    required: false
    default: "true"
  install-uv:
    description: Install the 'uv' package manager
    required: false
    default: "true"
  just-version:
    description: Version of 'just' to install if 'install-just' is true
    required: false
    default: "1.46.0"
  uv-version-file:
    description: Path to the file containing the 'uv' version to install if 'install-uv' is true
    required: false
    default: ""
  python-version:
    description: Python version to install with 'uv' if 'install-uv' is true
    required: false
    default: "3.14"

runs:
  using: composite
  steps:
    - name: Install Just
      if: ${{ inputs.install-just == 'true' }}
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      with:
        just-version: ${{ inputs.just-version }}

    - name: Install uv and set the Python version
      if: ${{ inputs.install-uv == 'true' }}
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        version-file: ${{ inputs.uv-version-file }}
        enable-cache: false # Cache disabled as a safety measure against cache-poisoning attacks
        python-version: ${{ inputs.python-version }}
