# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
"""LiteHRNet model implementations."""

from __future__ import annotations

from typing import Any

from torch import nn

from otx.algo.segmentation.backbones import LiteHRNet as _LiteHRNet
from otx.algo.segmentation.heads import CustomFCNHead
from otx.algo.utils.support_otx_v1 import OTXv1Helper
from otx.core.model.segmentation import OTXSegmentationModel

from .base_model import BaseSegmNNModel


class OTXLiteHRNet(OTXSegmentationModel):
    """LiteHRNet Model."""
    def _create_model(self) -> nn.Module:
        backbone = _LiteHRNet(**self.backbone_configuration)
        decode_head = CustomFCNHead(num_classes=self.num_classes, **self.decode_head_configuration)
        return BaseSegmNNModel(
            backbone=backbone,
            decode_head=decode_head,
            pretrained_weights=self.pretrained_weights,
            criterion_configuration=self.criterion_configuration,
        )

    def load_from_otx_v1_ckpt(self, state_dict: dict, add_prefix: str = "model.model.") -> dict:
        """Load the previous OTX ckpt according to OTX2.0."""
        return OTXv1Helper.load_seg_lite_hrnet_ckpt(state_dict, add_prefix)

    @property
    def _optimization_config(self) -> dict[str, Any]:
        """PTQ config for LiteHRNet."""
        # TODO(Kirill): check PTQ without adding the whole backbone to ignored_scope
        ignored_scope = self._obtain_ignored_scope()
        optim_config = {
            "advanced_parameters": {
                "activations_range_estimator_params": {
                    "min": {"statistics_type": "QUANTILE", "aggregator_type": "MIN", "quantile_outlier_prob": 1e-4},
                    "max": {"statistics_type": "QUANTILE", "aggregator_type": "MAX", "quantile_outlier_prob": 1e-4},
                },
            },
        }
        optim_config.update(ignored_scope)
        return optim_config

    def _obtain_ignored_scope(self) -> dict[str, Any]:
        """Returns the ignored scope for the model based on the litehrnet version."""
        if self.model_name == "litehrnet_18":
            ignored_scope_names = [
                "/model/backbone/stage0/stage0.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.0/Add_1",
                "/model/backbone/stage0/stage0.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.1/Add_1",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.0/Add_1",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.0/Add_2",
                "/model/backbone/stage1/stage1.0/Add_5",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.1/Add_1",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.1/Add_2",
                "/model/backbone/stage1/stage1.1/Add_5",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.2/Add_1",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.2/Add_2",
                "/model/backbone/stage1/stage1.2/Add_5",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.3/Add_1",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.3/Add_2",
                "/model/backbone/stage1/stage1.3/Add_5",
                "/model/backbone/stage2/stage2.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.0/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.0/layers/layers.0/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.0/Add_1",
                "/model/backbone/stage2/stage2.0/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.0/Add_2",
                "/model/backbone/stage2/stage2.0/layers/layers.1/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.0/Add_3",
                "/model/backbone/stage2/stage2.0/Add_6",
                "/model/backbone/stage2/stage2.0/Add_7",
                "/model/backbone/stage2/stage2.0/Add_11",
                "/model/backbone/stage2/stage2.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.1/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.1/layers/layers.0/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.1/Add_1",
                "/model/backbone/stage2/stage2.1/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.1/Add_2",
                "/model/backbone/stage2/stage2.1/layers/layers.1/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.1/Add_3",
                "/model/backbone/stage2/stage2.1/Add_6",
                "/model/backbone/stage2/stage2.1/Add_7",
                "/model/backbone/stage2/stage2.1/Add_11",
                "/model/aggregator/Add",
                "/model/aggregator/Add_1",
                "/model/aggregator/Add_2",
                "/model/backbone/stage2/stage2.1/Add",
            ]

            return {
                "ignored_scope": {
                    "patterns": ["/model/backbone/*"],
                    "names": ignored_scope_names,
                },
                "preset": "mixed",
            }

        if self.model_name == "litehrnet_s":
            ignored_scope_names = [
                "/model/backbone/stage0/stage0.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.0/Add_1",
                "/model/backbone/stage0/stage0.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.1/Add_1",
                "/model/backbone/stage0/stage0.2/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.2/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.2/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.2/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.2/Add_1",
                "/model/backbone/stage0/stage0.3/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.3/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.3/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.3/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.3/Add_1",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.0/Add_1",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.0/Add_2",
                "/model/backbone/stage1/stage1.0/Add_5",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.1/Add_1",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.1/Add_2",
                "/model/backbone/stage1/stage1.1/Add_5",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.2/Add_1",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.2/Add_2",
                "/model/backbone/stage1/stage1.2/Add_5",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.3/Add_1",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.3/Add_2",
                "/model/backbone/stage1/stage1.3/Add_5",
                "/model/aggregator/Add",
                "/model/aggregator/Add_1",
            ]

            return {
                "ignored_scope": {
                    "names": ignored_scope_names,
                },
                "preset": "mixed",
            }

        if self.model_name == "litehrnet_x":
            ignored_scope_names = [
                "/model/backbone/stage0/stage0.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.0/Add_1",
                "/model/backbone/stage0/stage0.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage0/stage0.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage0/stage0.1/Add_1",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.0/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.0/Add_1",
                "/model/backbone/stage1/stage1.0/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.0/Add_2",
                "/model/backbone/stage1/stage1.0/Add_5",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.1/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.1/Add_1",
                "/model/backbone/stage1/stage1.1/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.1/Add_2",
                "/model/backbone/stage1/stage1.1/Add_5",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.2/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.2/Add_1",
                "/model/backbone/stage1/stage1.2/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.2/Add_2",
                "/model/backbone/stage1/stage1.2/Add_5",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.3/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage1/stage1.3/Add_1",
                "/model/backbone/stage1/stage1.3/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage1/stage1.3/Add_2",
                "/model/backbone/stage1/stage1.3/Add_5",
                "/model/backbone/stage2/stage2.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.0/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.0/layers/layers.0/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.0/Add_1",
                "/model/backbone/stage2/stage2.0/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.0/Add_2",
                "/model/backbone/stage2/stage2.0/layers/layers.1/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.0/Add_3",
                "/model/backbone/stage2/stage2.0/Add_6",
                "/model/backbone/stage2/stage2.0/Add_7",
                "/model/backbone/stage2/stage2.0/Add_11",
                "/model/backbone/stage2/stage2.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.1/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.1/layers/layers.0/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.1/Add_1",
                "/model/backbone/stage2/stage2.1/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.1/Add_2",
                "/model/backbone/stage2/stage2.1/layers/layers.1/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.1/Add_3",
                "/model/backbone/stage2/stage2.1/Add_6",
                "/model/backbone/stage2/stage2.1/Add_7",
                "/model/backbone/stage2/stage2.1/Add_11",
                "/model/backbone/stage2/stage2.2/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.2/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.2/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.2/layers/layers.0/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.2/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.2/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.2/Add_1",
                "/model/backbone/stage2/stage2.2/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.2/Add_2",
                "/model/backbone/stage2/stage2.2/layers/layers.1/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.2/Add_3",
                "/model/backbone/stage2/stage2.2/Add_6",
                "/model/backbone/stage2/stage2.2/Add_7",
                "/model/backbone/stage2/stage2.2/Add_11",
                "/model/backbone/stage2/stage2.3/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.3/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.3/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.3/layers/layers.0/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.3/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage2/stage2.3/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage2/stage2.3/Add_1",
                "/model/backbone/stage2/stage2.3/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage2/stage2.3/Add_2",
                "/model/backbone/stage2/stage2.3/layers/layers.1/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage2/stage2.3/Add_3",
                "/model/backbone/stage2/stage2.3/Add_6",
                "/model/backbone/stage2/stage2.3/Add_7",
                "/model/backbone/stage2/stage2.3/Add_11",
                "/model/backbone/stage3/stage3.0/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage3/stage3.0/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage3/stage3.0/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage3/stage3.0/layers/layers.0/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage3/stage3.0/layers/layers.0/cross_resolution_weighting/Mul_4",
                "/model/backbone/stage3/stage3.0/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage3/stage3.0/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage3/stage3.0/Add_1",
                "/model/backbone/stage3/stage3.0/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage3/stage3.0/Add_2",
                "/model/backbone/stage3/stage3.0/layers/layers.1/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage3/stage3.0/Add_3",
                "/model/backbone/stage3/stage3.0/layers/layers.1/cross_resolution_weighting/Mul_4",
                "/model/backbone/stage3/stage3.0/Add_4",
                "/model/backbone/stage3/stage3.0/Add_7",
                "/model/backbone/stage3/stage3.0/Add_8",
                "/model/backbone/stage3/stage3.0/Add_9",
                "/model/backbone/stage3/stage3.0/Add_13",
                "/model/backbone/stage3/stage3.0/Add_14",
                "/model/backbone/stage3/stage3.0/Add_19",
                "/model/backbone/stage3/stage3.1/layers/layers.0/cross_resolution_weighting/Mul",
                "/model/backbone/stage3/stage3.1/layers/layers.0/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage3/stage3.1/layers/layers.0/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage3/stage3.1/layers/layers.0/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage3/stage3.1/layers/layers.0/cross_resolution_weighting/Mul_4",
                "/model/backbone/stage3/stage3.1/layers/layers.1/cross_resolution_weighting/Mul",
                "/model/backbone/stage3/stage3.1/layers/layers.1/cross_resolution_weighting/Mul_1",
                "/model/backbone/stage3/stage3.1/Add_1",
                "/model/backbone/stage3/stage3.1/layers/layers.1/cross_resolution_weighting/Mul_2",
                "/model/backbone/stage3/stage3.1/Add_2",
                "/model/backbone/stage3/stage3.1/layers/layers.1/cross_resolution_weighting/Mul_3",
                "/model/backbone/stage3/stage3.1/Add_3",
                "/model/backbone/stage3/stage3.1/layers/layers.1/cross_resolution_weighting/Mul_4",
                "/model/backbone/stage3/stage3.1/Add_4",
                "/model/backbone/stage3/stage3.1/Add_7",
                "/model/backbone/stage3/stage3.1/Add_8",
                "/model/backbone/stage3/stage3.1/Add_9",
                "/model/backbone/stage3/stage3.1/Add_13",
                "/model/backbone/stage3/stage3.1/Add_14",
                "/model/backbone/stage3/stage3.1/Add_19",
                "/model/backbone/stage0/stage0.0/Add",
                "/model/backbone/stage0/stage0.1/Add",
                "/model/backbone/stage1/stage1.0/Add",
                "/model/backbone/stage1/stage1.1/Add",
                "/model/backbone/stage1/stage1.2/Add",
                "/model/backbone/stage1/stage1.3/Add",
                "/model/backbone/stage2/stage2.0/Add",
                "/model/backbone/stage2/stage2.1/Add",
                "/model/backbone/stage2/stage2.2/Add",
                "/model/backbone/stage2/stage2.3/Add",
                "/model/backbone/stage3/stage3.0/Add",
                "/model/backbone/stage3/stage3.1/Add",
            ]

            return {
                "ignored_scope": {
                    "patterns": ["/model/aggregator/*"],
                    "names": ignored_scope_names,
                },
                "preset": "performance",
            }

        return {}
