id: object-detection-dfine-x
name: D-FINE-X

pretrained_weights:
  source: direct_link
  url: https://github.com/eugene123tw/DEIM/releases/download/poc/deim_dfine_hgnetv2_x_coco_50e.pth
  sha_sum: e729436f96d95e78dbf67452bf3fb654cd5bed37de43067f5cf0aafb24d0fc7a

description: "D-FINE is a powerful real-time object detector that redefines the bounding box regression task in DETRs as Fine-grained Distribution Refinement (FDR). Combined with the DEIM adaptive augmentation scheduling framework (enabled by default), it achieves outstanding performance with faster convergence."
stats:
  gigaflops: 202
  trainable_parameters: 62
  benchmark_metrics:
    coco_map_50_95: 56.5
    coco_map_50: 74.0

hyperparameters:
  training:
    learning_rate: 0.0005
    weight_decay: 0.000125
    scheduler:
      factor: 0.5
      patience: 6
      warmup:
        enable: true
        epochs: 30
    allowed_values_input_size:
      - 640
    input_size_width: 640
    input_size_height: 640
  dataset_preparation:
    augmentation:
      deim_framework: true
      random_zoom_out:
        enable: true
