id: object-detection-dfine-m
name: D-FINE-M

pretrained_weights:
  source: direct_link
  url: https://github.com/eugene123tw/DEIM/releases/download/poc/deim_dfine_hgnetv2_m_coco_90e.pth
  sha_sum: 2b6cd0582a4aa711f583982057b7fb0f3daebdd98e4dc168824714014c3219bc

description: "D-FINE is a powerful real-time object detector that redefines the bounding box regression task in DETRs as Fine-grained Distribution Refinement (FDR). Combined with the DEIM adaptive augmentation scheduling framework (enabled by default), it achieves outstanding performance with faster convergence."
stats:
  gigaflops: 57
  trainable_parameters: 19
  benchmark_metrics:
    coco_map_50_95: 52.7

hyperparameters:
  training:
    learning_rate: 0.0004
    weight_decay: 0.0001
    scheduler:
      factor: 0.5
      patience: 15
      warmup:
        enable: true
        epochs: 30
    allowed_values_input_size:
      - 640
    input_size_width: 640
    input_size_height: 640
  dataset_preparation:
    augmentation:
      deim_framework: true
      random_zoom_out:
        enable: true
