id: object-detection-dinov3-detr-s
name: DINOv3-DETR-S

pretrained_weights:
  source: direct_link
  url: https://github.com/kprokofi/DEIMv2/releases/download/1.0.0/deimv2_dinov3_s_coco.pth
  sha_sum: 9491ab33b68ecfc0e34043abb3009599ab1e892fb953a1faad12ef4fca5a35c4

description: "DINOv3-DETR is an efficient end-to-end object detection transformer that leverages the DEIMv2 training framework with a DINOv3 backbone, achieving strong accuracy with fewer parameters."
stats:
  gigaflops: 25.6
  trainable_parameters: 9.7
  benchmark_metrics:
    coco_map_50_95: 50.9

hyperparameters:
  training:
    learning_rate: 0.0004
    weight_decay: 0.0001
    scheduler:
      factor: 0.5
      patience: 10
      warmup:
        enable: true
        epochs: 30
    allowed_values_input_size:
      - 640
    input_size_width: 640
    input_size_height: 640
  dataset_preparation:
    augmentation:
      deim_framework: true
      random_zoom_out:
        enable: true
