id: object-detection-edgecrafter-l
name: ECDet-L
license: EdgeCrafter

pretrained_weights:
  source: direct_link
  url: https://github.com/capsule2077/edgecrafter/releases/download/edgecrafterv1/ecdet_l.pth
  sha_sum: 60e48c51b33d70acf8e3a3faddbdb70b0876c64509b74cb623106cc7c31e85a1

description: "EdgeCrafter detection model (ECDet-L) combines an efficient ECViT backbone with a hybrid encoder and transformer decoder for real-time, high-accuracy object detection with low latency."

stats:
  gigaflops: 101.0
  trainable_parameters: 31.0
  benchmark_metrics:
    coco_map_50_95: 57.0

capabilities:
  tiling: false

hyperparameters:
  training:
    learning_rate: 0.0005
    weight_decay: 0.0001
    batch_size: 4
    accumulate_grad_batches: 8
    early_stopping:
      patience: 10
    scheduler:
      factor: 0.5
      patience: 10
    gradient_clip:
      enable: true
      max_grad_norm: 0.1
    allowed_values_input_size:
      - 640
    input_size_width: 640
    input_size_height: 640
  dataset_preparation:
    augmentation:
      deim_framework: true
      random_zoom_out:
        enable: true
