id: object-detection-rfdetr-l
name: RF-DETR-L

pretrained_weights:
  source: direct_link
  url: https://storage.googleapis.com/rfdetr/rf-detr-large-2026.pth
  cache_filename: rf-detr-large-2026.pth
  sha_sum: 0f4e20e19a99c0f8a62b5685f57f6c8b5c371c59081feda6752a0561a79ccf38

description: "RF-DETR is a real-time object detection model that combines a DINOv2 vision transformer backbone with a novel decoder for high-accuracy detection without NMS post-processing."
stats:
  gigaflops: 94.9
  trainable_parameters: 33.9
  benchmark_metrics:
    coco_map_50_95: 56.5
    coco_map_50: 75.1

hyperparameters:
  training:
    learning_rate: 0.0001
    weight_decay: 0.0001
    batch_size: 4
    early_stopping:
      patience: 15
    scheduler:
      factor: 0.1
      patience: 10
    gradient_clip:
      enable: true
      max_grad_norm: 0.1
    allowed_values_input_size:
      - 320
      - 448
      - 512
      - 576
      - 640
      - 704
      - 768
      - 896
    input_size_width: 704
    input_size_height: 704
  dataset_preparation:
    augmentation:
      random_zoom_out:
        enable: true
        fill: 0
        side_range:
          - 1.0
          - 4.0
        probability: 0.5
