id: object-detection-rt-detr-r50
name: RT-DETR-R50

pretrained_weights:
  source: direct_link
  url: https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r50vd_2x_coco_objects365_from_paddle.pth
  sha_sum: 7788173453f771d45d0b49ffa23dbeb60796ccb8425afa52befb0b8fe033608c

description: "RT-DETR is a real-time object detection algorithm based on the transformer architecture. It combines a convolutional backbone with an efficient encoder-decoder transformer to directly predict object classes and bounding boxes without the need for anchor boxes or NMS."
stats:
  gigaflops: 136
  trainable_parameters: 42
  benchmark_metrics:
    coco_map_50_95: 53.1
    coco_map_50: 71.3

hyperparameters:
  dataset_preparation:
    augmentation:
      iou_random_crop:
        enable: false
        probability: 1.0
  training:
    learning_rate: 0.0001
    weight_decay: 0.0001
    scheduler:
      factor: 0.1
      patience: 6
      warmup:
        enable: true
        epochs: 100
    input_size_width: 640
    input_size_height: 640
