id: object-detection-yolox-x
name: YOLOX-X

pretrained_weights:
  source: direct_link
  url: https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_x_8x8_300e_coco/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth
  sha_sum: 1ef88d67f9c912a7c3a6df4f4d9bdf391cf70df867e6c9d7f249c7a3990e3dec

description: "YOLOX is a high-performance, anchor-free object detection algorithm that builds on the YOLO series with modern improvements. It features a decoupled head for separate classification and regression tasks, strong data augmentation techniques, and advanced label assignment strategies. YOLOX achieves a great balance between speed and accuracy, making it suitable for real-time applications across various domains."
stats:
  gigaflops: 281.9
  trainable_parameters: 99.1
  benchmark_metrics:
    coco_map_50_95: 51.5
    coco_map_50: 69.6

hyperparameters:
  dataset_preparation:
    augmentation:
      mosaic:
        enable: true
      mixup:
        enable: true
        probability: 0.5
        alpha: 1.5
      iou_random_crop:
        enable: false
        probability: 1.0
        min_scale: 0.3
        max_scale: 1.0
      color_jitter:
        enable: true
        brightness:
          - 0.875
          - 1.125
        contrast:
          - 0.5
          - 1.5
        saturation:
          - 0.5
          - 1.5
        hue:
          - -0.05
          - 0.05
        probability: 0.5
      random_horizontal_flip:
        enable: true
        probability: 0.5
      random_vertical_flip:
        enable: false
        probability: 0.5
      random_affine:
        enable: true
        max_rotate_degree: 10.0
        max_translate_ratio: 0.1
        scaling_ratio_range:
          - 1.0
          - 1.0
        max_shear_degree: 2.0
        probability: 0.7
      gaussian_blur:
        enable: false
        kernel_size: 5
        sigma:
          - 0.1
          - 2.0
        probability: 0.5
      gaussian_noise:
        enable: false
        mean: 0.0
        sigma: 0.1
        probability: 0.5
      random_erasing:
        enable: false
        scale:
          - 0.02
          - 0.33
        ratio:
          - 0.3
          - 3.3
        probability: 0.5
        value: 0.0
      random_grayscale:
        enable: false
        probability: 0.1
      random_sharpness:
        enable: false
        sharpness: 0.5
        probability: 0.5
  training:
    learning_rate: 0.001
    weight_decay: 0.0001
    scheduler:
      factor: 0.1
      patience: 4
    gradient_clip:
      enable: true
      max_grad_norm: 35.0
    input_size_width: 640
    input_size_height: 640
