id: object-detection-yolox-l
name: YOLOX-L

pretrained_weights:
  source: direct_link
  url: https://download.openmmlab.com/mmdetection/v2.0/yolox/yolox_l_8x8_300e_coco/yolox_l_8x8_300e_coco_20211126_140236-d3bd2b23.pth
  sha_sum: d3bd2b23e4cd178bfcc756df67e0d0949f3d77e0a73482f6da694c580ed54da1

description: "YOLOX is a high-performance, anchor-free object detection algorithm that builds on the YOLO series with modern improvements. It features a decoupled head for separate classification and regression tasks, strong data augmentation techniques, and advanced label assignment strategies. YOLOX achieves a great balance between speed and accuracy, making it suitable for real-time applications across various domains."
stats:
  gigaflops: 155.6
  trainable_parameters: 54.2
  benchmark_metrics:
    coco_map_50_95: 50.2
    coco_map_50: 68.5

hyperparameters:
  dataset_preparation:
    augmentation:
      mosaic:
        enable: true
      mixup:
        enable: true
        probability: 0.5
        alpha: 1.5
      iou_random_crop:
        enable: false
        probability: 1.0
        min_scale: 0.3
        max_scale: 1.0
      color_jitter:
        enable: true
        brightness:
          - 0.875
          - 1.125
        contrast:
          - 0.5
          - 1.5
        saturation:
          - 0.5
          - 1.5
        hue:
          - -0.05
          - 0.05
        probability: 0.5
      random_horizontal_flip:
        enable: true
        probability: 0.5
      random_vertical_flip:
        enable: false
        probability: 0.5
      random_affine:
        enable: true
        max_rotate_degree: 10.0
        max_translate_ratio: 0.1
        scaling_ratio_range:
          - 1.0
          - 1.0
        max_shear_degree: 2.0
        probability: 0.7
      gaussian_blur:
        enable: false
        kernel_size: 5
        sigma:
          - 0.1
          - 2.0
        probability: 0.5
      gaussian_noise:
        enable: false
        mean: 0.0
        sigma: 0.1
        probability: 0.5
      random_erasing:
        enable: false
        scale:
          - 0.02
          - 0.33
        ratio:
          - 0.3
          - 3.3
        probability: 0.5
        value: 0.0
      random_grayscale:
        enable: false
        probability: 0.1
      random_sharpness:
        enable: false
        sharpness: 0.5
        probability: 0.5
  training:
    learning_rate: 0.001
    weight_decay: 0.0001
    scheduler:
      factor: 0.1
      patience: 4
    gradient_clip:
      enable: true
      max_grad_norm: 35.0
    input_size_width: 640
    input_size_height: 640
