FROM ubuntu:20.04@sha256:bb1c41682308d7040f74d103022816d41c50d7b0c89e9d706a74b4e548636e54

ARG PYTHON_VER=3.9
ARG SOURCE=https://download.pytorch.org/whl/cpu
ENV DEBIAN_FRONTEND=noninteractive

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install --no-install-recommends -y ca-certificates && \
    apt-get install --no-install-recommends -y curl python${PYTHON_VER} python${PYTHON_VER}-dev python${PYTHON_VER}-distutils g++ ffmpeg libsm6 libxext6 libgl1-mesa-glx && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python${PYTHON_VER} get-pip.py && \
    rm get-pip.py && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /mnt/shared

WORKDIR /training_extensions
COPY . /training_extensions

RUN ln -s /mnt/shared ./shared

# hadolint ignore=SC2102
RUN pip install --no-cache-dir --require-hashes --no-deps -r docker/requirements.txt && \
    pip install --no-cache-dir -e .[full]

CMD ["/bin/bash"]
