ARG http_proxy
ARG https_proxy
ARG no_proxy

FROM python:3.10-slim-bullseye@sha256:f9d945b64f64eea6c7976c8ab75dc49df24801f822ce1cd24680d2fc9598feeb

RUN pip install --no-cache-dir mlflow==2.8.1 psycopg2-binary==2.9.9
