/**
 * @overview WebSocket messages events
 * @copyright (c) JSC Intel A/O
 */

export const WS = {
  ON: {
    PROBLEM_LIST: 'PROBLEM_LIST',
    PROBLEM_DETAILS: 'PROBLEM_DETAILS',
    PROBLEM_CREATE: 'PROBLEM_CREATE',
    MODEL_EVALUATE: 'MODEL_EVALUATE',
    MODEL_LIST: 'MODEL_LIST',
    BUILD_LIST: 'BUILD_LIST',
    ASSET_FIND_IN_FOLDER: 'ASSET_FIND_IN_FOLDER',
    ASSET_SETUP_TO_CVAT: 'ASSET_SETUP_TO_CVAT',
    ASSET_DUMP_ANNOTATION: 'ASSET_DUMP_ANNOTATION',
    BUILD_UPDATE_ASSET_STATE: 'BUILD_UPDATE_ASSET_STATE',
    BUILD_CREATE: 'BUILD_CREATE'
  },
  SEND: {
    PROBLEM_LIST: 'PROBLEM_LIST',
    PROBLEM_DETAILS: 'PROBLEM_DETAILS',
    PROBLEM_CREATE: 'PROBLEM_CREATE',
    MODEL_EVALUATE: 'MODEL_EVALUATE',
    MODEL_LIST: 'MODEL_LIST',
    BUILD_LIST: 'BUILD_LIST',
    MODEL_FINE_TUNE: 'MODEL_FINE_TUNE',
    ASSET_FIND_IN_FOLDER: 'ASSET_FIND_IN_FOLDER',
    ASSET_SETUP_TO_CVAT: 'ASSET_SETUP_TO_CVAT',
    ASSET_DUMP_ANNOTATION: 'ASSET_DUMP_ANNOTATION',
    BUILD_UPDATE_ASSET_STATE: 'BUILD_UPDATE_ASSET_STATE',
    BUILD_CREATE: 'BUILD_CREATE'
  }
};
