id: image-classification-yolo26-l
name: YOLO26-L
license: AGPL-3.0

pretrained_weights:
  source: direct_link
  url: https://huggingface.co/Ultralytics/YOLO26/resolve/main/yolo26l-cls.pt
  mirror_url: https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo26l-cls.pt
  sha_sum: "7a3aebb7de6f5d79f0153da627a5f68bd3d7df30e648c0fdb7f9217986ee129e"

description: "YOLO26-L is the large Ultralytics YOLO26 classification model. It offers high accuracy while using the Geti Tune data pipeline for preprocessing and dataset handling."
stats:
  gigaflops: 6.2
  trainable_parameters: 14.1
  benchmark_metrics:
    imagenet_top1_accuracy: 79.0
    imagenet_top5_accuracy: 94.6

hyperparameters:
  training:
    learning_rate: 0.000714
    weight_decay: 0.0005
    max_epochs: 90
    early_stopping:
      enable: false
    batch_size: 16
    input_size_width: 224
    input_size_height: 224
    scheduler:
      type: cosine_annealing
      warmup:
        enable: true
        epochs: 3
    gradient_clip:
      enable: true
      max_grad_norm: 10.0
    gradient_accumulation:
      enable: false
  dataset_preparation:
    augmentation:
      random_resize_crop:
        crop_ratio_range:
          - 0.5
          - 1.0
      random_erasing:
        enable: true
        probability: 0.4
