task: MULTI_CLASS_CLS
model:
  class_path: getitune.backend.lightning.models.classification.multiclass_models.timm_model.TimmModelMulticlassCls
  init_args:
    label_info: 1000
    model_name: tf_efficientnet_b0.ap_in1k

    optimizer:
      class_path: torch.optim.SGD
      init_args:
        lr: 0.0049
        momentum: 0.9
        weight_decay: 0.0001

    scheduler:
      class_path: getitune.backend.lightning.schedulers.LinearWarmupSchedulerCallable
      init_args:
        num_warmup_steps: 0
        main_scheduler_callable:
          class_path: lightning.pytorch.cli.ReduceLROnPlateau
          init_args:
            mode: max
            factor: 0.5
            patience: 3
            monitor: val/f1-score

engine:
  device: auto

callback_monitor: val/f1-score

data: ../../_base_/data/classification.yaml

callbacks:
  - class_path: getitune.backend.lightning.callbacks.adaptive_early_stopping.EarlyStoppingWithWarmup
    init_args:
      patience: 5
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: "" # use engine.work_dir
      monitor: val/f1-score
      mode: max
      save_top_k: 1
      save_last: true
      auto_insert_metric_name: false
      filename: "checkpoints/epoch_{epoch:03d}"

overrides:
  max_epochs: 90
