backend: huggingface
task: MULTI_CLASS_CLS

model:
  class_path: getitune.backend.huggingface.models.classification.HFMulticlassClsModel
  init_args:
    checkpoint: google/vit-base-patch16-224
    pretrained: true

engine:
  device: auto

training:
  max_epochs: 90
  batch: 64
  learning_rate: 0.0001
  precision: bf16-mixed
  patience: 10
  optim: adamw_torch
  weight_decay: 0.05
  lr_scheduler_type: cosine
  warmup_ratio: 0.1
  max_grad_norm: 1.0

data: ../../_base_/data/classification.yaml
