task: MULTI_LABEL_CLS
model:
  class_path: getitune.backend.lightning.models.classification.multilabel_models.timm_model.TimmModelMultilabelCls
  init_args:
    label_info: 1000
    model_name: DYNAMIC

    optimizer:
      class_path: getitune.backend.lightning.models.classification.optimizers.timm.TimmOptimizer
      init_args:
        lr: .nan
        weight_decay: .nan

engine:
  device: auto

callback_monitor: val/map

data: ../../_base_/data/classification.yaml

callbacks:
  - class_path: getitune.backend.lightning.callbacks.adaptive_early_stopping.EarlyStoppingWithWarmup
    init_args:
      patience: 5
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: ""
      monitor: val/f1-score
      mode: max
      save_top_k: 1
      save_last: true
      auto_insert_metric_name: false
      filename: "checkpoints/epoch_{epoch:03d}"

overrides:
  max_epochs: 90
